### ISSUE TITLE
Mentioning gives incorrect url

### ISSUE THREAD

**Issue by Reddiepoint** [SubZeroPL/cs-rin-ru-enhanced-mod#73]
Sometimes when I click the mention button it gives the wrong post link: `@[url=https://cs.rin.ru/forum/memberlist.php?mode=viewprofile&u=CORRECTID]CORRECT USERNAME[/url], Re: [url=https://cs.rin.ru/forum/viewtopic.php?p=nread#pnread]Post[/url]. `
I have no idea what causes it. I am using the beta version with change topic to last post and when you go to an unread topic it has a chance of doing that.

**Comment by vCybah** [comment]
Hi, I've seen this `https://cs.rin.ru/forum/viewtopic.php?p=nread#pnread` link very often when I'm using the copy link button as well, and have to refresh the page or sometimes manually switch to the previous page and then switch back etc.. to get the proper link to copy. 

Is it possible it might have something to do with the infinite scrolling? When I'm updating the OP of a thread I'll be scrolling with the infinite loading/scrolling and finding posts to link in the OP, and if I scroll through a "next page load" and click the copy link button on somebody's post, sometimes it will work fine but a lot of times it gives me this link. 

Most of the time I've just been going directly to the page the post is on and scrolling down to it (so it doesn't auto load the next page) to copy the link and it works fine then. I'm not sure if this is what's causing it (infinite scrolling) or something else but just wanted to drop this here since it's possibly related. I've had this issue for a while but never thought of reporting it since it's not a very big deal and I assumed it only happens to me since I didn't see any reports etc..

I haven't tested too much what causes it or anything just noticed it a lot over my time using this script.

I just realized I was on an outdated version so I updated to the beta (https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/commit/e7d14ebbf599a8e2f00f884c33d39dac9edebac9) but now the buttons in question are just click-able text for me. 
[Image](https://ibb.co/jT04FYc)

They were actually working fine up until today (looking nice, matching the quote/edit buttons) and then I made a post and they went away and changed to this (before updating to the beta). It may just be on my end and if so, my bad, just wanted to bring it up in case it happens to anyone else. 
Updating to the beta has the same result, no more buttons, just text. It's just a visual thing as clicking the text still works fine.
Sorry if this is already known/I missed the proper issue for it.

Thanks for the great script guys!
