### ISSUE TITLE
Infinite scroll bug on PM folders with more than 100 messages

### ISSUE THREAD

**Issue by Christsnatcher** [SubZeroPL/cs-rin-ru-enhanced-mod#76]
Heyo,

just spotted that enabling "Infinite scrolling" (all other options disabled) duplicates the bottom-most element on any PM folder that holds at least 101 messages, as depicted here:

https://gyazo.com/5972b5fd38fee82c0ae955748e29708c

No big issue, still worth a mention here. Keep up the great work guys! ;)

**Comment by Altansar69** [comment]
Hello, it's a pleasure to see you using our script ;).
All bugs are important!
I've just corrected the problem, in the beta branch, and created a pull request so that the changes are here too.
https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/pull/77

**Comment by SubZeroPL** [comment]
Hi @Christsnatcher.
Does this duplicate line appear immediately after opening PM folder, or only after you try to scroll the list to load next messages?
Unrelated: my god, you have over 100 pages of PMs? I have only 72 (PMs, not pages) so can't reproduce ;)

**Comment by Altansar69** [comment]
Scroll. It's from infinite scrolls. It's from the last update where I brought back the reply topic button. To do this, when you get to the last page, I copy the button at the top and put it at the bottom. But I hadn't thought of the private messages page, that's why there are 2 times the bottom line. I've just added a condition so that this element won't be copied if we're on the inbox page.
Wow, I hadn't seen that. That's a lot of posts. I only have 3 pages myself
