### ISSUE TITLE
Enable two-way infinite scrolling

### ISSUE THREAD

**Issue by SubZeroPL** [SubZeroPL/cs-rin-ru-enhanced-mod#9]
Should work not only for next pages but also for previous ones

**Comment by Pocokk** [comment]
Now and then, I realize how much I "miss" this feature, the infinite scrolling is an awesome thing on its own, but backwards would be quite a feat as well!

**Comment by Altansar69** [comment]
how could we do it? Because the content of the next page is loaded when you get to the bottom of the page. But we couldn't really do the opposite and say that we load the previous page when we arrive at the top, given that on a topic we're basically at the very top of the page. That would mean loading the front page in any case.

**Comment by SubZeroPL** [comment]
Done in #19
